{ config, options, ... }:

let
  domain = "mail.ozguryazilimhacettepe.com";
in
{
  services.nginx.virtualHosts."${domain}".enableACME = true;
  security.acme.certs."${domain}".group = "maddy";
  users.groups."maddy" = {
    members = [ "maddy" "nginx" ];
  };

  # TODO: I'd much prefer PAM authentication here, but I could not get it to work.
  networking.firewall.allowedTCPPorts = [ 993 465 ];
  services.maddy = {
    enable = true;
    openFirewall = true;

    tls = {
      loader = "file";
      certificates = [
        {
          certPath = "${config.security.acme.certs.${domain}.directory}/cert.pem";
          keyPath = "${config.security.acme.certs.${domain}.directory}/key.pem";
        }
      ];
    };

    hostname = domain;
    primaryDomain = "ozguryazilimhacettepe.com";
    localDomains = [ "ozguryazilimhacettepe.com" "lists.tlkg.org.tr" ];
    config = ''
      auth.pass_table local_authdb {
          table sql_table {
              driver sqlite3
              dsn credentials.db
              table_name passwords
          }
      }

      storage.imapsql local_mailboxes {
        driver sqlite3
        dsn imapsql.db
      }

      table.chain local_rewrites {
        optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
        optional_step static {
            entry postmaster postmaster@$(primary_domain)
        }
        optional_step file /etc/maddy/aliases
      }

      msgpipeline local_routing {
          # Insert handling for special-purpose local domains here.
          # e.g.
          # destination lists.example.org {
          #     deliver_to lmtp tcp://127.0.0.1:8024
          # }

          destination lists.tlkg.org.tr {
              deliver_to lmtp tcp://127.0.0.1:8024
          }

          destination postmaster $(local_domains) {
              modify {
                  replace_rcpt &local_rewrites
              }

              deliver_to &local_mailboxes
          }

          default_destination {
              reject 550 5.1.1 "User doesn't exist"
          }
      }

      smtp tcp://0.0.0.0:25 {
          limits {
              # Up to 20 msgs/sec across max. 10 SMTP connections.
              all rate 20 1s
              all concurrency 10
          }

          dmarc yes
          check {
              require_mx_record
              dkim
              spf
          }

          source $(local_domains) {
              reject 501 5.1.8 "Use Submission for outgoing SMTP"
          }
          default_source {
              destination postmaster $(local_domains) {
                  deliver_to &local_routing
              }
              default_destination {
                  reject 550 5.1.1 "User doesn't exist"
              }
          }
      }

      submission tls://0.0.0.0:465 tcp://0.0.0.0:587 {
          limits {
              # Up to 50 msgs/sec across any amount of SMTP connections.
              all rate 50 1s
          }

          auth &local_authdb

          source $(local_domains) {
              check {
                  authorize_sender {
                      prepare_email &local_rewrites
                      user_to_email identity
                  }
              }

              destination postmaster $(local_domains) {
                  deliver_to &local_routing
              }
              default_destination {
                  modify {
                      dkim $(primary_domain) $(local_domains) default
                  }
                  deliver_to &remote_queue
              }
          }
          default_source {
              reject 501 5.1.8 "Non-local sender domain"
          }
      }

      target.remote outbound_delivery {
          limits {
              # Up to 20 msgs/sec across max. 10 SMTP connections
              # for each recipient domain.
              destination rate 20 1s
              destination concurrency 10
          }
          mx_auth {
              dane
              mtasts {
                  cache fs
                  fs_dir mtasts_cache/
              }
              local_policy {
                  min_tls_level encrypted
                  min_mx_level none
              }
          }
      }

      target.queue remote_queue {
          target &outbound_delivery

          autogenerated_msg_domain $(primary_domain)
          bounce {
              destination postmaster $(local_domains) {
                  deliver_to &local_routing
              }
              default_destination {
                  reject 550 5.0.0 "Refusing to send DSNs to non-local addresses"
              }
          }
      }

      # ----------------------------------------------------------------------------
      # IMAP endpoints

      imap tls://0.0.0.0:993 tcp://0.0.0.0:143 {
          auth &local_authdb
          storage &local_mailboxes
      }

      # SMTP for mailman
      # TODO: This should not be exposed to the whole server?
      smtp tcp://127.0.0.1:2525 {
          destination postmaster lists.tlkg.org.tr {
              deliver_to &local_routing
          }
          default_destination {
              deliver_to &remote_queue
          }
      }
  '';
  };

  services.mailman = {
    enable = true;
    enablePostfix = false;
    siteOwner = "mailman@div72.xyz";
    webHosts = [ "lists.tlkg.org.tr" ];
    hyperkitty.enable = true;
    serve.enable = true;
    settings = {
      mta = {
        # FIXME: This should not be necessary for null mta?
        configuration = "/dev/null";

        incoming = "mailman.mta.null.NullMTA";
        lmtp_host = "127.0.0.1";
        lmtp_port = "8024";

        outgoing = "mailman.mta.deliver.deliver";
        smtp_host = "127.0.0.1";
        smtp_port = "2525";
      };
    };
    webSettings = {
      DEFAULT_FROM_EMAIL = "noreply@lists.tlkg.org.tr";
      SERVER_EMAIL = "noreply@lists.tlkg.org.tr";
    };
  };

  # This is necessary as services.mailman.serve.enable does not turn on TLS.
  services.nginx.virtualHosts."lists.tlkg.org.tr" = {
    enableACME = true;
    forceSSL = true;
  };
}
