#!/usr/bin/env bash

title="$1"
title_len="${#title}"
text=$(cat)
longest_line_len=$(wc -L <<< "$text")

total_mid_len=$(($longest_line_len - $title_len - 2))
left_mid_len=$(($total_mid_len / 2))
right_mid_len=$(($total_mid_len - $left_mid_len))

# repeat "<string>" <n>
repeat() {
  printf "%.s$1" $(seq $2)
}

# Mobile browsers do not seem to handle unicode monospace properly. Use ascii.
if [[ "$MOBILE" == 1 ]]; then

printf "+%s| %s |%s+\n" "$(repeat "-" $left_mid_len)" "$title" "$(repeat "-" $right_mid_len)"

xargs -d $'\n' -I{} printf "| %-${longest_line_len}s |\n" "{}" <<< "$text"

printf "+%s+" "$(repeat "-" $(($longest_line_len + 2)))"

else

printf "╔%s╣ %s ╠%s╗\n" "$(repeat "═" $left_mid_len)" "$title" "$(repeat "═" $right_mid_len)"

xargs -d $'\n' -I{} printf "║ %-${longest_line_len}s ║\n" "{}" <<< "$text"

printf "╚%s╝" "$(repeat "═" $(($longest_line_len + 2)))"

fi
